import { combineReducers } from 'redux';
import LibraryReducer from './LibraryReducer'
import SelectionReducer from './SelectionReducer'

// Value of libraries will be generated by the LibraryReducer
export default combineReducers({
  libraries: LibraryReducer,
  selectedLibraryId: SelectionReducer
});
